### ISSUE TITLE
完成实验后的时间单位错误

### ISSUE THREAD

**Issue by muou000** [ztearroo/cheat-obrsim#2]
应该是秒，但是显示分钟（应该？）
ps:我也想contribute，但是就这么一个字错了，只好来issue了/doge

**Comment by ztearroo** [comment]
指的是代码中的minute变量吗，这个变量实际上的值就是用的秒

**Comment by muou000** [comment]
> 指的是代码中的minute变量吗，这个变量实际上的值就是用的秒

对，但是日志显示分钟![40e38422-2ff9-4aab-9fa9-12544bac4202.png](https://github.com/user-attachments/assets/21a511f9-734d-4d17-9517-7871175a429c)

**Comment by muou000** [comment]
> 指的是代码中的minute变量吗，这个变量实际上的值就是用的秒

《我真不是强迫症》

**Comment by ztearroo** [comment]
源码已push，release比较懒，没有重新编译
